export const mutations ={
    SOCKET_ONOPEN: 'Sockets/SOCKET_ONOPEN',
    SOCKET_ONCLOSE: 'Sockets/SOCKET_ONCLOSE',
    SOCKET_ONERROR: 'Sockets/SOCKET_ONERROR',
    SOCKET_ONMESSAGE: 'Sockets/SOCKET_ONMESSAGE',
    SOCKET_RECONNECT: 'Sockets/SOCKET_RECONNECT',
    SOCKET_RECONNECT_ERROR: 'Sockets/SOCKET_RECONNECT_ERROR'
}
